#### Dependencies

In [1]:
import numpy as np

#### Input Dataset

In [2]:
X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])

#### Target output

In [3]:
y = np.array([[0,1,1,0]]).T


### Neural Network architecture

#### layer1 = L0
#### layer2 = L1
#### layer3 = L2


![Image of NN architecture](https://cdn-images-1.medium.com/max/1000/1*kA1fcHpG4ZvdHzVZ_UuKyA.png)

####  Initialise Weight Matrices for layer 1 and layer 2

In [4]:

np.random.seed(1)
w_L0_2_L1 = 2 * np.random.random((3, 4)) -1
w_L1_2_L2  = 2 * np.random.random((4,1)) - 1

#### Define NonLinearity (Activation Function) and its Derivative

In [5]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
def sigmoid_derivative(x):
    return x * (1 - x)

#### Training code to Optimize Network on the Dataset

In [6]:
for i in range(1,60001):
    
    #forward pass:
    l0 = X
    
    l1 = sigmoid(np.dot(l0, w_L0_2_L1))
    
    l2 = sigmoid(np.dot(l1, w_L1_2_L2))
   


    #calculate network error
    
    l2_error = y - l2 
    
    
    if i % 10000 == 0:
        
        print("Training Error : {} at Epoch {}".format(np.mean(np.abs(l2_error)),i))
    
    # Backward pass:
    
    # update the non- confident predictions and mute the confident predictions 
    
    l2_delta = l2_error * sigmoid_derivative(l2)
    
    # the error contribution of l1 on l2
    
    l1_error = l2_delta.dot(w_L1_2_L2.T)
    
    # update the non- confident predictions and mute the confident predictions
        
    l1_delta = l1_error * sigmoid_derivative(l1)
    
    #Update weight matrices 
    
    w_L1_2_L2 +=  l1.T.dot(l2_delta)
    
    w_L0_2_L1 +=  l0.T.dot(l1_delta)
print("\n")   
print(" Accuracy : ",l2 , " after ",str(i)+" Epochs",sep ="\n")

Training Error : 0.0085850250975033 at Epoch 10000
Training Error : 0.0057896210643503185 at Epoch 20000
Training Error : 0.004629261152181438 at Epoch 30000
Training Error : 0.003958818824398139 at Epoch 40000
Training Error : 0.0035101602765980986 at Epoch 50000
Training Error : 0.00318353073559491 at Epoch 60000


 Accuracy : 
[[0.00260572]
 [0.99672209]
 [0.99701711]
 [0.00386759]]
 after 
60000 Epochs


In [7]:
l2 = str(l2)
print("Target Output : ",  y, "actual output: ", l2,sep ="\n")

Target Output : 
[[0]
 [1]
 [1]
 [0]]
actual output: 
[[0.00260572]
 [0.99672209]
 [0.99701711]
 [0.00386759]]
